# @package model

# Model configuration for Aria VIO training
_target_: src.models.vio_module.VIOLitModule

# Optimizer configuration - will be instantiated by Lightning with model parameters
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 1e-4

# Scheduler configuration  
scheduler: null

# Loss function - Use WeightedMSEPoseLoss for better pose training
criterion:
  _target_: src.metrics.weighted_loss.WeightedMSEPoseLoss
  angle_weight: 100

# Network architecture - Use PoseTransformer
net:
  _target_: src.models.components.pose_transformer.PoseTransformer
  input_dim: 768
  embedding_dim: 128
  num_layers: 2
  nhead: 8
  dim_feedforward: 512
  dropout: 0.1

compile: false
