# @package model

# AR/VR Optimized VIFT Configuration
# Combines deep transformer architecture with AR/VR specific loss functions
_target_: src.models.vio_module.VIOLitModule

# Optimizer configuration - tuned for AR/VR
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 1e-4

# Scheduler configuration with warm restarts
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  T_0: 25
  T_mult: 1

# AR/VR Specialized Loss Function - THE INNOVATION! 🚀
criterion:
  _target_: src.metrics.arvr_loss.ARVRUltimateLosse

# Network architecture - Deep transformer (proven best)
net:
  _target_: src.models.components.pose_transformer.PoseTransformer
  input_dim: 768
  embedding_dim: 768  # Large embedding for complex AR/VR patterns
  num_layers: 4       # Deep network for representational capacity
  nhead: 6           # Fewer heads, larger per head
  dim_feedforward: 512
  dropout: 0.1       # Regularization for generalization

# Simple evaluation for fast iteration
metrics_calculator:
  _target_: src.metrics.dummy_metrics_calculator.DummyMetricsCalculator

tester:
  _target_: src.testers.dummy_tester.DummyTester

compile: false