_target_: src.models.vio_module.VIOLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  T_0: 25
  T_mult: 1

criterion:
  _target_: torch.nn.MSELoss

net:
  _target_: src.models.components.pose_transformer.PoseTransformer
  input_dim: 768
  embedding_dim: 768
  num_layers: 4
  nhead: 6
  dim_feedforward: 128
  dropout: 0.0

# Use the AR/VR metrics calculator
metrics_calculator:
  _target_: src.metrics.arvr_kitti_metrics_calculator.ARVRKITTIMetricsCalculator

# Configure tester for all 4 Aria sequences with proper paths
tester:
  _target_: src.testers.kitti_latent_tester.KITTILatentTester
  val_seqs: ['016', '017', '018', '019']  # All 4 Aria sequences
  data_dir: ${paths.data_dir}/kitti_data
  seq_len: 11  # 11-frame windows like KITTI
  folder: sequences
  img_w: 512  # Images will be resized to this width
  img_h: 256  # Images will be resized to this height
  wrapper_weights_path: ${paths.root_dir}/pretrained_models/vf_512_if_256_3e-05.model
  device: cuda
  v_f_len: 512
  i_f_len: 256
  use_history_in_eval: False

compile: false