# @package model

# Model configuration for MultiHead VIO with fixed quaternion handling
_target_: src.models.multihead_vio_separate_fixed.MultiHeadVIOModelSeparate

# Model hyperparameters
visual_dim: 512
imu_dim: 256
hidden_dim: 256
num_shared_layers: 4
num_specialized_layers: 3
num_heads: 8
dropout: 0.1
learning_rate: 0.0001
weight_decay: 1e-5
rotation_weight: 1.0
translation_weight: 1.0
velocity_weight: 0.3
sequence_length: 10

# Metrics calculator for evaluation
metrics_calculator:
  _target_: src.metrics.kitti_metrics_calculator.KITTIMetricsCalculator

# Tester for evaluation
tester:
  _target_: src.testers.kitti_latent_tester.KITTILatentTester
  val_seqs: ['00', '01', '02']
  data_dir: aria_latent_data/test_5
  seq_len: 11
  folder: sequences
  img_w: 512
  img_h: 256
  wrapper_weights_path: ${paths.root_dir}/pretrained_models/vf_512_if_256_3e-05.model
  device: 'mps'  # Change to 'cuda' if using GPU
  v_f_len: 512
  i_f_len: 256

compile: false